In [139]:
# Step 1: Import the Pandas library for data manipulation.
import pandas as pd

In [140]:
# Step 2: Load the Exchange Rate dataset into a DataFrame.
df = pd.read_excel("Exchange rate, new LCU per USD extended backward, period average.xlsx")

In [141]:
# Step 3: Inspect the dataset to understand its structure and identify relevant columns.
df.head()

,Unnamed: 0,Afghanistan,Angola,Albania,Advanced Economies,United Arab Emirates,Argentina,Armenia,Antigua and Barbuda,Australia,...,"Venezuela, RB",Viet Nam,Vanuatu,World (WBG members),Samoa,Kosovo,"Yemen, Rep.",South Africa,Zambia,Zimbabwe
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1997.0,47.50000,228814.800000,148.6727,42.59214,3.672193,0.999992,490.8467,2.696925,1.347961,...,0.484018,11667.96,115.8155,NaN,1.356314,NaN,121.5939,4.606554,1.297396,NaN
2,1998.0,47.50000,273251.900000,152.4996,57.33443,3.673000,1.000000,504.9150,2.697102,1.591508,...,0.541740,13255.24,127.8731,NaN,0.341372,NaN,129.9111,5.528227,1.818064,NaN
3,1999.0,46.62167,168333.900000,137.4677,49.21741,3.672881,0.999656,535.0617,2.697299,1.549667,...,0.605929,13934.26,129.1716,NaN,0.694723,NaN,145.2801,6.112958,2.433617,NaN
4,2000.0,47.35667,9.427331,143.8515,46.97218,3.672996,0.999891,539.5258,2.688208,1.725241,...,0.679871,14166.81,137.8611,NaN,3.274839,NaN,159.6970,6.942925,3.273040,NaN

In [142]:
df.head(
)

,Unnamed: 0,Afghanistan,Angola,Albania,Advanced Economies,United Arab Emirates,Argentina,Armenia,Antigua and Barbuda,Australia,...,"Venezuela, RB",Viet Nam,Vanuatu,World (WBG members),Samoa,Kosovo,"Yemen, Rep.",South Africa,Zambia,Zimbabwe
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1997.0,47.50000,228814.800000,148.6727,42.59214,3.672193,0.999992,490.8467,2.696925,1.347961,...,0.484018,11667.96,115.8155,NaN,1.356314,NaN,121.5939,4.606554,1.297396,NaN
2,1998.0,47.50000,273251.900000,152.4996,57.33443,3.673000,1.000000,504.9150,2.697102,1.591508,...,0.541740,13255.24,127.8731,NaN,0.341372,NaN,129.9111,5.528227,1.818064,NaN
3,1999.0,46.62167,168333.900000,137.4677,49.21741,3.672881,0.999656,535.0617,2.697299,1.549667,...,0.605929,13934.26,129.1716,NaN,0.694723,NaN,145.2801,6.112958,2.433617,NaN
4,2000.0,47.35667,9.427331,143.8515,46.97218,3.672996,0.999891,539.5258,2.688208,1.725241,...,0.679871,14166.81,137.8611,NaN,3.274839,NaN,159.6970,6.942925,3.273040,NaN

In [143]:
# Step 4: Rename the year column for consistency across all datasets.
df = df.rename(columns={"Unnamed: 0": "Year"})

In [144]:
df.head()

,Year,Afghanistan,Angola,Albania,Advanced Economies,United Arab Emirates,Argentina,Armenia,Antigua and Barbuda,Australia,...,"Venezuela, RB",Viet Nam,Vanuatu,World (WBG members),Samoa,Kosovo,"Yemen, Rep.",South Africa,Zambia,Zimbabwe
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1997.0,47.50000,228814.800000,148.6727,42.59214,3.672193,0.999992,490.8467,2.696925,1.347961,...,0.484018,11667.96,115.8155,NaN,1.356314,NaN,121.5939,4.606554,1.297396,NaN
2,1998.0,47.50000,273251.900000,152.4996,57.33443,3.673000,1.000000,504.9150,2.697102,1.591508,...,0.541740,13255.24,127.8731,NaN,0.341372,NaN,129.9111,5.528227,1.818064,NaN
3,1999.0,46.62167,168333.900000,137.4677,49.21741,3.672881,0.999656,535.0617,2.697299,1.549667,...,0.605929,13934.26,129.1716,NaN,0.694723,NaN,145.2801,6.112958,2.433617,NaN
4,2000.0,47.35667,9.427331,143.8515,46.97218,3.672996,0.999891,539.5258,2.688208,1.725241,...,0.679871,14166.81,137.8611,NaN,3.274839,NaN,159.6970,6.942925,3.273040,NaN

In [145]:
# Step 5: Keep only the Year and India columns required for analysis.
df= df[["Year", "India"]]

In [146]:
# Step 6: Rename the indicator column to a meaningful variable name.
df= df.rename(columns={"India": "Exchange rate"})

In [147]:
df.head()

     Year  Exchange rate
0     NaN            NaN
1  1997.0       36.32046
2  1998.0       41.23745
3  1999.0       43.05785
4  2000.0       44.94066

In [148]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Year           30 non-null     float64
 1   Exchange rate  30 non-null     float64
dtypes: float64(2)
memory usage: 628.0 bytes

In [149]:
# Step 7: Remove unnecessary rows and convert the Year column to integer format.
df= df.drop(0)

In [150]:
df.head()

     Year  Exchange rate
1  1997.0       36.32046
2  1998.0       41.23745
3  1999.0       43.05785
4  2000.0       44.94066
5  2001.0       47.17988

In [151]:
df["Year"] = df["Year"].astype(int)
df.head()

   Year  Exchange rate
1  1997       36.32046
2  1998       41.23745
3  1999       43.05785
4  2000       44.94066
5  2001       47.17988

In [152]:
# Step 8: Save the cleaned dataset for later merging.
import os

os.makedirs("data/cleaned", exist_ok=True)

df.to_csv("data/cleaned/exchange_rate.csv", index= False)

Repeating the above steps for other indictors.

In [153]:
pd.read_csv("data/cleaned/exchange_rate.csv").head()

   Year  Exchange rate
0  1997       36.32046
1  1998       41.23745
2  1999       43.05785
3  2000       44.94066
4  2001       47.17988

In [154]:

df= pd.read_excel("CPI Price, % y-o-y, nominal, seas. adj..xlsx")

In [155]:
df.head()

,Unnamed: 0,Albania,United Arab Emirates,Armenia,Austria,Azerbaijan,Belgium,Bangladesh,Bulgaria,Bahrain,...,Tunisia,Turkey,"Taiwan, China",Uganda,Uruguay,United States,Viet Nam,Kosovo,South Africa,Zambia
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1997.0,33.117360,NaN,14.095580,1.354218,NaN,1.628530,5.190311,NaN,NaN,...,3.673005,85.74947,0.906290,NaN,19.812530,2.337566,NaN,NaN,8.571950,24.34053
2,1998.0,20.564450,NaN,8.460263,0.949775,NaN,0.925261,8.283493,11.105780,NaN,...,3.119611,84.50260,1.686130,-1.108623,10.794950,1.547007,NaN,NaN,6.887284,24.62231
3,1999.0,0.402084,NaN,0.898525,0.621910,NaN,1.128581,6.251726,2.591905,NaN,...,2.690787,64.79626,0.178509,5.752463,5.654575,2.193139,NaN,NaN,5.195662,26.74749
4,2000.0,0.064854,NaN,-0.739210,2.282092,NaN,2.546894,2.374996,10.326650,NaN,...,2.945966,54.88033,1.251455,3.378306,4.769861,3.366683,NaN,NaN,5.348392,26.06838

In [156]:
df = df.drop(0).reset_index(drop=True)

In [157]:
df.head(10)

,Unnamed: 0,Albania,United Arab Emirates,Armenia,Austria,Azerbaijan,Belgium,Bangladesh,Bulgaria,Bahrain,...,Tunisia,Turkey,"Taiwan, China",Uganda,Uruguay,United States,Viet Nam,Kosovo,South Africa,Zambia
0,1997.0,33.117360,NaN,14.095580,1.354218,NaN,1.628530,5.190311,NaN,NaN,...,3.673005,85.749470,0.906290,NaN,19.812530,2.337566,NaN,NaN,8.571950,24.340530
1,1998.0,20.564450,NaN,8.460263,0.949775,NaN,0.925261,8.283493,11.105780,NaN,...,3.119611,84.502600,1.686130,-1.108623,10.794950,1.547007,NaN,NaN,6.887284,24.622310
2,1999.0,0.402084,NaN,0.898525,0.621910,NaN,1.128581,6.251726,2.591905,NaN,...,2.690787,64.796260,0.178509,5.752463,5.654575,2.193139,NaN,NaN,5.195662,26.747490
3,2000.0,0.064854,NaN,-0.739210,2.282092,NaN,2.546894,2.374996,10.326650,NaN,...,2.945966,54.880330,1.251455,3.378306,4.769861,3.366683,NaN,NaN,5.348392,26.068380
4,2001.0,3.083429,NaN,3.172856,2.665014,0.860324,2.464259,1.945414,7.376574,NaN,...,1.970089,54.363620,-0.002035,1.939510,4.377797,2.816629,NaN,NaN,5.692325,21.239710
5,2002.0,5.174473,NaN,1.038254,1.780863,2.776384,1.645522,3.362077,5.782152,NaN,...,2.735862,44.874920,-0.194303,-0.302284,13.957610,1.595670,1.872805,NaN,9.169462,22.298560
6,2003.0,2.376255,NaN,4.696658,1.334520,2.131814,1.590255,5.598892,2.353841,NaN,...,2.731640,25.293120,-0.282339,8.716368,19.401440,2.297999,3.220350,0.604710,5.675729,21.307260
7,2004.0,2.872909,NaN,6.858352,2.107112,6.708094,2.100769,7.578005,6.122873,NaN,...,3.647782,8.589539,1.601725,3.677143,9.167633,2.667572,7.764138,-1.054519,-0.697820,17.961370
8,2005.0,2.322974,NaN,0.486324,2.264259,9.526654,2.783413,7.028288,5.028359,NaN,...,1.998195,8.117273,2.300828,8.601203,4.698232,3.365830,8.280730,-1.374827,2.051955,18.304650
9,2006.0,2.408920,NaN,2.958767,1.387332,8.275392,1.785666,6.767402,7.245675,NaN,...,4.095046,9.602229,0.606770,7.214370,6.385676,3.222089,7.398378,0.637562,3.252462,9.064835

In [158]:
df=df.rename(columns={"Unnamed: 0": "Year" })

In [159]:
df.head()

,Year,Albania,United Arab Emirates,Armenia,Austria,Azerbaijan,Belgium,Bangladesh,Bulgaria,Bahrain,...,Tunisia,Turkey,"Taiwan, China",Uganda,Uruguay,United States,Viet Nam,Kosovo,South Africa,Zambia
0,1997.0,33.117360,NaN,14.095580,1.354218,NaN,1.628530,5.190311,NaN,NaN,...,3.673005,85.74947,0.906290,NaN,19.812530,2.337566,NaN,NaN,8.571950,24.34053
1,1998.0,20.564450,NaN,8.460263,0.949775,NaN,0.925261,8.283493,11.105780,NaN,...,3.119611,84.50260,1.686130,-1.108623,10.794950,1.547007,NaN,NaN,6.887284,24.62231
2,1999.0,0.402084,NaN,0.898525,0.621910,NaN,1.128581,6.251726,2.591905,NaN,...,2.690787,64.79626,0.178509,5.752463,5.654575,2.193139,NaN,NaN,5.195662,26.74749
3,2000.0,0.064854,NaN,-0.739210,2.282092,NaN,2.546894,2.374996,10.326650,NaN,...,2.945966,54.88033,1.251455,3.378306,4.769861,3.366683,NaN,NaN,5.348392,26.06838
4,2001.0,3.083429,NaN,3.172856,2.665014,0.860324,2.464259,1.945414,7.376574,NaN,...,1.970089,54.36362,-0.002035,1.939510,4.377797,2.816629,NaN,NaN,5.692325,21.23971

In [160]:
df= df[["Year", "India"]]

In [161]:
df.head()

     Year  India
0  1997.0    NaN
1  1998.0    NaN
2  1999.0    NaN
3  2000.0    NaN
4  2001.0    NaN

In [162]:
df= df.rename(columns={"India": "Inflation"})

In [163]:
df.head()

     Year  Inflation
0  1997.0        NaN
1  1998.0        NaN
2  1999.0        NaN
3  2000.0        NaN
4  2001.0        NaN

In [164]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Year       30 non-null     float64
 1   Inflation  25 non-null     float64
dtypes: float64(2)
memory usage: 612.0 bytes

In [165]:
df["Year"] = df["Year"].astype(int)

In [166]:
df.to_csv("data/cleaned/inflation.csv", index=False)

In [167]:

inflation = pd.read_csv("data/cleaned/inflation.csv")
inflation.head(10)

   Year  Inflation
0  1997        NaN
1  1998        NaN
2  1999        NaN
3  2000        NaN
4  2001        NaN
5  2002   5.206416
6  2003   4.339540
7  2004   3.853640
8  2005   3.739476
9  2006   6.061532

In [168]:
df = pd.read_excel("Industrial Production, constant 2010 US$, seas. adj..xlsx")

In [169]:
df.head(
)

,Unnamed: 0,Advanced Economies,Austria,Belgium,Bangladesh,Bulgaria,Bosnia and Herzegovina,Belarus,Brazil,Barbados,...,Tunisia,Turkey,Uganda,Ukraine,Uruguay,United States,Uzbekistan,Viet Nam,World (WBG members),South Africa
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1997.0,8.100000e+12,6.590000e+10,6.770000e+10,NaN,NaN,NaN,NaN,3.740000e+11,462000000.0,...,9.460000e+09,1.250000e+11,NaN,NaN,NaN,2.630000e+12,NaN,NaN,1.110000e+13,9.520000e+10
2,1998.0,8.250000e+12,7.150000e+10,6.970000e+10,NaN,NaN,NaN,NaN,3.670000e+11,492000000.0,...,1.010000e+10,1.280000e+11,NaN,NaN,NaN,2.780000e+12,NaN,NaN,1.130000e+13,9.440000e+10
3,1999.0,8.500000e+12,7.600000e+10,7.050000e+10,NaN,NaN,NaN,NaN,3.650000e+11,488000000.0,...,1.060000e+10,1.240000e+11,NaN,NaN,NaN,2.910000e+12,NaN,NaN,1.160000e+13,9.370000e+10
4,2000.0,8.920000e+12,8.340000e+10,7.610000e+10,NaN,8.690000e+09,NaN,NaN,3.890000e+11,480000000.0,...,1.100000e+10,1.310000e+11,NaN,NaN,NaN,3.010000e+12,NaN,NaN,1.230000e+13,9.780000e+10

In [170]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 91 columns):
 #   Column                                                  Non-Null Count  Dtype
---  ------                                                  --------------  -----
 0   Unnamed: 0                                              30 non-null     float64
 1   Advanced Economies                                      29 non-null     float64
 2   Austria                                                 29 non-null     float64
 3   Belgium                                                 29 non-null     float64
 4   Bangladesh                                              5 non-null      float64
 5   Bulgaria                                                26 non-null     float64
 6   Bosnia and Herzegovina                                  20 non-null     float64
 7   Belarus                                                 18 non-null     float64
 8   Brazil                                                  29 non-null     float64
 9   Barbados                                                17 non-null     float64
 10  Canada                                                  29 non-null     float64
 11  Chile                                                   29 non-null     float64
 12  China                                                   29 non-null     float64
 13  Colombia                                                29 non-null     float64
 14  Costa Rica                                              29 non-null     float64
 15  Cyprus                                                  29 non-null     float64
 16  Czech Republic                                          29 non-null     float64
 17  Germany                                                 29 non-null     float64
 18  Denmark                                                 29 non-null     float64
 19  Dominican Republic                                      15 non-null     float64
 20  EMDE East Asia & Pacific                                28 non-null     float64
 21  EMDE Europe & Central Asia                              29 non-null     float64
 22  Ecuador                                                 20 non-null     float64
 23  Egypt, Arab Rep.                                        16 non-null     float64
 24  Emerging Market and Developing Economies (EMDEs)        28 non-null     float64
 25  Spain                                                   29 non-null     float64
 26  Estonia                                                 28 non-null     float64
 27  Finland                                                 29 non-null     float64
 28  France                                                  29 non-null     float64
 29  United Kingdom                                          29 non-null     float64
 30  Greece                                                  29 non-null     float64
 31  Guatemala                                               16 non-null     float64
 32  High Income Countries                                   29 non-null     float64
 33  Honduras                                                22 non-null     float64
 34  Croatia                                                 29 non-null     float64
 35  Hungary                                                 29 non-null     float64
 36  Indonesia                                               29 non-null     float64
 37  India                                                   29 non-null     float64
 38  Ireland                                                 29 non-null     float64
 39  Iceland                                                 20 non-null     float64
 40  Israel                                                  29 non-null     float64
 41  Italy                                                   29 non-null     float64
 42  Jordan                                                  24 non-null     float64
 43  Japan                                                   29 non-null     float64
 44  Kazakhstan                                              27 non-null     float64
 45  Korea, Rep.                                             29 non-null     float64
 46  EMDE Latin America & Caribbean                          29 non-null     float64
 47  Low-Income Countries (LIC)                              14 non-null     float64
 48  Sri Lanka                                               16 non-null     float64
 49  Lithuania                                               29 non-null     float64
 50  Luxembourg                                              29 non-null     float64
 51  Latvia                                                  27 non-null     float64
 52  Mexico                                                  29 non-null     float64
 53  Middle-Income Countries (MIC)                           28 non-null     float64
 54  North Macedonia                                         26 non-null     float64
 55  Malta                                                   26 non-null     float64
 56  Montenegro                                              26 non-null     float64
 57  Mongolia                                                19 non-null     float64
 58  EMDE Middle East, North Africa, Afghanistan & Pakistan  15 non-null     float64
 59  Malawi                                                  19 non-null     float64
 60  Malaysia                                                29 non-null     float64
 61  Nicaragua                                               20 non-null     float64
 62  Netherlands                                             29 non-null     float64
 63  Norway                                                  29 non-null     float64
 64  Pakistan                                                28 non-null     float64
 65  Peru                                                    29 non-null     float64
 66  Philippines                                             29 non-null     float64
 67  Poland                                                  29 non-null     float64
 68  Portugal                                                29 non-null     float64
 69  Paraguay                                                17 non-null     float64
 70  Romania                                                 29 non-null     float64
 71  Russian Federation                                      29 non-null     float64
 72  EMDE South Asia                                         29 non-null     float64
 73  Singapore                                               29 non-null     float64
 74  El Salvador                                             29 non-null     float64
 75  Serbia                                                  29 non-null     float64
 76  EMDE Sub-Saharan Africa                                 29 non-null     float64
 77  Slovakia                                                29 non-null     float64
 78  Slovenia                                                29 non-null     float64
 79  Sweden                                                  29 non-null     float64
 80  Thailand                                                26 non-null     float64
 81  Tunisia                                                 29 non-null     float64
 82  Turkey                                                  29 non-null     float64
 83  Uganda                                                  15 non-null     float64
 84  Ukraine                                                 24 non-null     float64
 85  Uruguay                                                 24 non-null     float64
 86  United States                                           29 non-null     float64
 87  Uzbekistan                                              15 non-null     float64
 88  Viet Nam                                                18 non-null     float64
 89  World (WBG members)                                     29 non-null     float64
 90  South Africa                                            29 non-null     float64
dtypes: float64(91)
memory usage: 22.2 KB

In [171]:
df= df[["Unnamed: 0","India"]]

In [172]:
df= df.rename(columns={"Unnamed: 0": "Year"})
df= df.rename(columns={"India":"Industrial_Production"})

In [173]:
df.head()

     Year  Industrial_Production
0     NaN                    NaN
1  1997.0           2.110000e+11
2  1998.0           2.200000e+11
3  1999.0           2.330000e+11
4  2000.0           2.470000e+11

In [174]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 2 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Year                   30 non-null     float64
 1   Industrial_Production  29 non-null     float64
dtypes: float64(2)
memory usage: 628.0 bytes

In [176]:
df.to_csv("data/cleaned/industrial_production.csv", index=False)

In [177]:
df = pd.read_excel("Foreign Reserves, Months Import Cover, Goods.xlsx")

In [178]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Columns: 119 entries, Unnamed: 0 to Zambia
dtypes: float64(119)
memory usage: 28.9 KB

In [179]:
df.head()

,Unnamed: 0,Albania,Advanced Economies,Armenia,Australia,Austria,Burundi,Belgium,Bangladesh,Bulgaria,...,Uganda,Ukraine,Uruguay,United States,"Venezuela, RB",Viet Nam,World (WBG members),Samoa,South Africa,Zambia
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1997.0,0.633393,0.291661,NaN,0.274096,0.316162,NaN,0.106448,NaN,0.245776,...,NaN,0.137796,NaN,0.082020,NaN,NaN,0.351717,NaN,NaN,NaN
2,1998.0,0.480174,0.298636,NaN,0.242538,0.342372,NaN,0.114842,NaN,0.302001,...,NaN,0.053961,NaN,0.093923,NaN,NaN,0.360787,NaN,NaN,NaN
3,1999.0,0.440481,0.290025,NaN,0.326749,0.226099,NaN,0.068839,NaN,0.297864,...,NaN,0.092827,NaN,0.071525,NaN,NaN,0.357185,NaN,NaN,NaN
4,2000.0,0.581966,0.280050,0.361323,0.269049,0.215247,0.227736,0.058529,NaN,0.294023,...,NaN,0.105978,0.716444,0.056320,0.931108,0.221957,0.338659,NaN,NaN,0.231412

In [180]:
df= df[["Unnamed: 0", "India"]]

In [181]:
df = df.rename(columns={"Unnamed: 0": "Year"})
df= df.rename(columns={"India": "Forex_Reserves"})

In [182]:
df.head()

     Year  Forex_Reserves
0     NaN             NaN
1  1997.0        0.659740
2  1998.0        0.699389
3  1999.0        0.743921
4  2000.0        0.777293

In [183]:
df= df.drop(0)

In [184]:
df.head()

     Year  Forex_Reserves
1  1997.0        0.659740
2  1998.0        0.699389
3  1999.0        0.743921
4  2000.0        0.777293
5  2001.0        0.955777

In [185]:
df["Year"]=df["Year"].astype(int)

In [186]:
df.head()

   Year  Forex_Reserves
1  1997        0.659740
2  1998        0.699389
3  1999        0.743921
4  2000        0.777293
5  2001        0.955777

In [187]:
df.to_csv("data/cleaned/forex_reserves.csv")

In [188]:
df= pd.read_excel("Exports Merchandise, Customs, current US$, millions, seas. adj..xlsx")

In [189]:
df.head()

,Unnamed: 0,Angola,Albania,Advanced Economies,Argentina,Australia,Austria,Azerbaijan,Burundi,Belgium,...,Uganda,Ukraine,Uruguay,United States,"Venezuela, RB",Viet Nam,World (WBG members),Samoa,South Africa,Zambia
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1996.0,5094.689,243.3936,4178369.0,23809.0,60233.37,57831.90,NaN,38.99173,175388.5,...,641.2139,14407.15,2.393407,625077.0,4609.314,6177.662,5200398.0,NaN,32502.69,721.1577
2,1997.0,5006.738,138.5836,4228564.0,26433.0,62835.03,58533.66,NaN,86.01044,171783.8,...,585.7458,14272.31,2.718810,689181.0,5375.105,7374.589,5342610.0,NaN,35207.32,394.0334
3,1998.0,3542.594,225.4329,4211427.0,26432.0,55899.17,62637.14,674.9803,65.00375,178992.1,...,513.7654,12672.46,2.765210,682137.0,5200.876,9414.929,5342100.0,NaN,29475.55,507.7683
4,1999.0,5155.554,262.5939,4295909.0,23310.0,55976.20,64162.50,1012.4520,54.00983,179023.2,...,479.4672,11560.96,2.238186,695797.0,4177.778,9907.149,5467808.0,NaN,30414.38,713.9374

In [190]:
df = df[["Unnamed: 0", "India"]]

In [191]:
df = df.rename(columns={"Unnamed: 0": "Year"})
df= df.rename(columns={"India": "Exports"})

In [192]:
df.head()

     Year   Exports
0     NaN       NaN
1  1996.0  1170.504
2  1997.0  1269.848
3  1998.0  1378.671
4  1999.0  1536.025

In [193]:
df = df.drop(0)

In [194]:
df.head()

     Year   Exports
1  1996.0  1170.504
2  1997.0  1269.848
3  1998.0  1378.671
4  1999.0  1536.025
5  2000.0  1909.391

In [195]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 1 to 30
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Year     30 non-null     float64
 1   Exports  29 non-null     float64
dtypes: float64(2)
memory usage: 612.0 bytes

In [196]:
df["Year"] = df["Year"].astype(int)

In [197]:
df.to_csv("data/cleaned/exports.csv")

In [198]:
df= pd.read_excel("GDP at market prices, constant 2010 US$, millions, seas. adj..xlsx")

In [199]:
df = df[["Unnamed: 0", "India"]]

In [200]:
df.head()

   Unnamed: 0     India
0         NaN       NaN
1      1997.0  608093.5
2      1998.0  644683.9
3      1999.0  689324.5
4      2000.0  728354.6

In [201]:
df = df.drop(0)

In [202]:
df = df.rename(columns={"Unnamed: 0": "Year"})
df= df.rename(columns={"India": "GDP"})

In [203]:
df.head()

     Year       GDP
1  1997.0  608093.5
2  1998.0  644683.9
3  1999.0  689324.5
4  2000.0  728354.6
5  2001.0  756637.5

In [204]:
df.to_csv("data/cleaned/gdp.csv")